name: nginx

on:
  push:
    paths:
      - 'nginx/**'
  pull_request:
    paths:
      - 'nginx/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: update git repo and restart nginx
        run: /usr/share/nginx/octopus-report.de/lab/update-git.sh && systemctl reload nginx
